# Cloud init file to use with multipass
package_update: true
packages:
  - git
  - make
  - vim
  - zip
  - curl
  - wget
  - python3-dev
  - python3-venv
  - python3-pip
  - podman
  - libgeos-dev

runcmd:
  - echo "alias docker=/usr/bin/podman" >> /home/ubuntu/.bashrc
